language: java
sudo: required
dist: trusty

addons:
  chrome: stable

before_install:
 - sudo apt-get install -y acl ecryptfs-utils mhddfs samba samba-common-bin
 - sudo mount -o remount,acl /
 - sudo service samba start

install: true

script:
  - mvn clean install